[workspace]
members = [
  "apps/desktop/src-tauri",
  "crates/core-analysis",
  "crates/core-carddb",
  "crates/core-domain",
  "crates/core-gamestate",
  "crates/core-parser",
  "crates/core-store",
  "crates/core-sync",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"
